const prdData = [
  {
    id: 1,
    name: 'Void Ring 01',
    img: '/imgs/cont1_prd1.png',
    subImgs: ['/imgs/cont1_prd1_detail1.png', '/imgs/cont1_prd1_detail2.png'],
    desc: '59,000',
    shortDesc: '비어 있는 공간이 만드는 존재감',
    detailImg1: '/imgs/cont1_prd1.png',
    shortDesc2:
      'Void 컬렉션은 형태 안의 공간을 통해 조용하지만 분명한 조형을 만들어냅니다',
    detailImg2: '/imgs/cont1_prd1_detail1.png',
  },
  {
    id: 2,
    name: 'Linear Band',
    img: '/imgs/cont1_prd2.png',
    subImgs: ['/imgs/cont1_prd2_detail1.png', '/imgs/cont1_prd2_detail2.png'],
    desc: '59,000',
    shortDesc: '가장 단순한 시작, 하나의 선',
    detailImg1: '/imgs/cont1_prd2.png',
    shortDesc2:
      'Linear 컬렉션은 공간 속에 놓인 하나의 선이 만들어내는 구조와 균형을 탐구합니다.',
    detailImg2: '/imgs/cont1_prd2_detail1.png',
  },
  {
    id: 3,
    name: 'Linear Drop',
    img: '/imgs/cont1_prd3.png',
    subImgs: ['/imgs/cont1_prd3_detail1.png', '/imgs/cont1_prd3_detail2.png'],
    desc: '59,000',
    shortDesc: '하나의 선에서 시작된 구조',
    detailImg1: '/imgs/cont1_prd3.png',
    shortDesc2:
      'Linear 컬렉션은 공간 속에 놓인 하나의 선이 만들어내는 구조와 균형을 탐구합니다',
    detailImg2: '/imgs/cont1_prd3_detail2.png',
  },
  {
    id: 4,
    name: 'Offset Drop',
    img: '/imgs/cont1_prd4.png',
    subImgs: ['/imgs/cont1_prd4_detail1.png', '/imgs/cont1_prd4_detail2.png'],
    desc: '59,000',
    shortDesc: '의도적인 비대칭',
    detailImg1: '/imgs/cont1_prd4.png',
    shortDesc2:
      'Offset 컬렉션은 중심에서 벗어난 구조가 만드는 새로운 균형을 탐구합니다',
    detailImg2: '/imgs/cont1_prd5_detail2.png',
  },
  {
    id: 5,
    name: 'Linear Twist',
    img: '/imgs/cont1_prd5.png',
    subImgs: ['/imgs/cont1_prd5_detail1.png', '/imgs/cont1_prd5_detail2.png'],
    desc: '59,000',
    shortDesc: '가장 단순한 시작, 하나의 선',
    detailImg1: '/imgs/cont1_prd5.png',
    shortDesc2:
      'Linear 컬렉션은 공간 속에 놓인 하나의 선이 만들어내는 구조와 균형을 탐구합니다',
    detailImg2: '/imgs/cont1_prd5_detail1.png',
  },
  {
    id: 6,
    name: 'Frame Band 01',
    img: '/imgs/cont1_prd6.png',
    subImgs: ['/imgs/cont1_prd6_detail1.png', '/imgs/cont1_prd6_detail2.png'],
    desc: '109,000',
    shortDesc: '경계로 완성되는 구조',
    detailImg1: '/imgs/cont1_prd6.png',
    shortDesc2:
      'Frame 컬렉션은 비어 있는 공간을 감싸는 선과 면의 구조를 탐구합니다',
    detailImg2: '/imgs/cont1_prd6_detail2.png',
  },
  {
    id: 7,
    name: 'Frame Band 02',
    img: '/imgs/cont1_prd7.png',
    subImgs: ['/imgs/cont1_prd7_detail1.png', '/imgs/cont1_prd7_detail2.png'],
    desc: '99,000',
    shortDesc: '경계로 완성되는 구조',
    detailImg1: '/imgs/cont1_prd7.png',
    shortDesc2:
      'Frame 컬렉션은 비어 있는 공간을 감싸는 선과 면의 구조를 탐구합니다',
    detailImg2: '/imgs/cont1_prd7_detail2.png',
  },
  {
    id: 8,
    name: 'Loop Drop',
    img: '/imgs/cont1_prd8.png',
    subImgs: ['/imgs/cont1_prd8_detail1.png', '/imgs/cont1_prd8_detail2.png'],
    desc: '59,000',
    shortDesc: '이어지고 다시 돌아오는 선',
    detailImg1: '/imgs/cont1_prd8.png',
    shortDesc2: 'Loop 컬렉션은 하나의 선이 이어지며 완결되는 구조를 표현합니다',
    detailImg2: '/imgs/cont1_prd8_detail2.png',
  },
  {
    id: 9,
    name: 'Void Ring 02',
    img: '/imgs/cont1_prd9.png',
    subImgs: ['/imgs/cont1_prd9_detail1.png', '/imgs/cont1_prd9_detail2.png'],
    desc: '59,000',
    shortDesc: '비어 있는 공간이 만드는 존재감',
    detailImg1: '/imgs/cont1_prd9.png',
    shortDesc2:
      'Void 컬렉션은 형태 안의 공간을 통해 조용하지만 분명한 조형을 만들어냅니다',
    detailImg2: '/imgs/cont1_prd9_detail2.png',
  },
];

export { prdData };
