const prdData = [
  { id: 1, name: 'Void Ring 01', 
    img: '/imgs/cont1_prd1.png', 
    subImgs: ['/imgs/cont1_prd1.png', '/imgs/cont1_prd1.png'], 
    desc: '59,000',shortDesc: '설명 문구 한 줄',
    detailImg1: '/imgs/cont1_prd1.png', 
    shortDesc2: '설명 문구 한 줄',
    detailImg2: '/imgs/cont1_prd1.png',},
  { id: 2, name: 'Linear Band', 
    img: '/imgs/cont1_prd2.png', 
    subImgs: ['/imgs/cont1_prd2.png', '/imgs/cont1_prd2.png'], 
    desc: '59,000',shortDesc: '설명 문구 한 줄',
    detailImg1: '/imgs/cont1_prd2.png', 
    shortDesc2: '설명 문구 한 줄',
    detailImg2: '/imgs/cont1_prd2.png',},
  { id: 3, name: 'Linear Drop', 
    img: '/imgs/cont1_prd3.png', 
    subImgs: ['/imgs/cont1_prd3.png', '/imgs/cont1_prd3.png'], 
    desc: '59,000',shortDesc: '설명 문구 한 줄',
    detailImg1: '/imgs/cont1_prd3.png', 
    shortDesc2: '설명 문구 한 줄',
    detailImg2: '/imgs/cont1_prd3.png', },
  { id: 4, name: 'Offset Drop', 
    img: '/imgs/cont1_prd4.png', 
    subImgs: ['/imgs/cont1_prd4.png', '/imgs/cont1_prd4.png'], 
    desc: '59,000',shortDesc: '설명 문구 한 줄',
    detailImg1: '/imgs/cont1_prd4.png', 
    shortDesc2: '설명 문구 한 줄',
    detailImg2: '/imgs/cont1_prd4.png'
   },
   { id: 5, name: 'Linear Twist', 
    img: '/imgs/cont1_prd5.png', 
    subImgs: ['/imgs/cont1_prd5.png', '/imgs/cont1_prd5.png'], 
    desc: '59,000',shortDesc: '설명 문구 한 줄',
    detailImg1: '/imgs/cont1_prd5.png', 
    shortDesc2: '설명 문구 한 줄',
    detailImg2: '/imgs/cont1_prd5.png' ,},
  {
    id: 6,
    name: 'Frame Band 01',
    img: '/imgs/cont1_prd6.png', 
    subImgs: ['/imgs/cont1_prd6.png', '/imgs/cont1_prd6.png'], 
    desc: '109,000',shortDesc: '설명 문구 한 줄',
    detailImg1: '/imgs/cont1_prd6.png', 
    shortDesc2: '설명 문구 한 줄',
    detailImg2: '/imgs/cont1_prd6.png',
  },
  { id: 7, name: 'Frame Band 02',
    img: '/imgs/cont1_prd7.png', 
    subImgs: ['/imgs/cont1_prd7.png', '/imgs/cont1_prd7.png'], 
    desc: '99,000',shortDesc: '설명 문구 한 줄',
    detailImg1: '/imgs/cont1_prd7.png', 
    shortDesc2: '설명 문구 한 줄',
    detailImg2: '/imgs/cont1_prd7.png',

  },
  { id: 8, name: 'Loop Drop', 
    img: '/imgs/cont1_prd8.png', 
    subImgs: ['/imgs/cont1_prd8.png', '/imgs/cont1_prd8.png'], 
    desc: '59,000',shortDesc: '설명 문구 한 줄',
    detailImg1: '/imgs/cont1_prd8.png', 
    shortDesc2: '설명 문구 한 줄',
    detailImg2: '/imgs/cont1_prd8.png',
   },
  { id: 9, name: 'Void Ring 02', 
    img: '/imgs/cont1_prd9.png', 
    subImgs: ['/imgs/cont1_prd9.png', '/imgs/cont1_prd9.png'], 
    desc: '59,000',shortDesc: '설명 문구 한 줄',
    detailImg1: '/imgs/cont1_prd9.png', 
    shortDesc2: '설명 문구 한 줄',
    detailImg2: '/imgs/cont1_prd9.png',
   },
];

  
export { prdData };
